---
- hosts: all
  user: ansible
  become: yes

  tasks:
  - service:
      name: ntpd
      state: stopped
  - command: ntpdate -b 0.centos.pool.ntp.org
  - service:
      name: ntpd
      state: started

...
